### PR TITLE
Added video resources to the Roadmap

### PR DESCRIPTION
**Pull request by Mrityunjayyshukla**
Added some Video Resources to the Roadmap for the beginners to follow along.
* For creating Flutter projects
* For creating Widgets
* Flutter Widgets
* Git/GitHub

### CODE REVIEW

**Comment by olexale** [comment]
Thank you for your PR!

The README file complements the roadmap by providing a curated *limited* set of links to articles, books, and videos on specific topics. A dedicated video section, however, goes against the original idea.

Regarding the "All Flutter Widgets" link, it looks like a good addition to Flutter's documentation. I'm happy to merge this PR if you could move the link below the "Package of the Week" playlist and remove the other links to maintain consistency with the roadmap's intent.

Thanks again for contributing!

**Comment by Mrityunjayyshukla** [comment]
Thank you for the feedback! I was considering adding the "All Flutter Widgets" link below "Package of the Week" and the "Git/GitHub Tutorial" link below "Interactive Git Learning Online", as Git/GitHub is also an integral part of the Roadmap. Do you think this arrangement aligns with the structure and flow of the resources?

**Review by Mrityunjayyshukla — COMMENTED** [review]
No requirement of a video section. Videos needed to be added in the existing topics

**Comment by olexale** [comment]
@Mrityunjayyshukla, just "All Flutter Widgets." I believe videos are much less useful than the interactive tutorial already on the list.
Thank you!

**Comment by Mrityunjayyshukla** [comment]
I've added "Flutter Widgets Playlist" below the "Package of the Week" in commit https://github.com/olexale/flutter_roadmap/pull/25/commits/45b88b29fd52d2ff0224ea4c82474e7913e7734d

**Comment by olexale** [comment]
Thank you!

**Pull request merged**
